# Generated by Django 3.2.8 on 2021-12-14 12:40

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='Success Stories'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='Testimonial'),
        ),
    ]
