# Generated by Django 3.2.8 on 2021-11-30 12:46

import django.db.models.deletion
import versatileimagefield.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("auth", "0012_alter_user_first_name_max_length")]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status"
                    ),
                ),
                ("email", models.EmailField(max_length=225, unique=True)),
                ("full_name", models.CharField(max_length=225)),
                ("dob", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "profile_for",
                    models.CharField(
                        choices=[
                            ("Self", "Self"),
                            ("Son", "Son"),
                            ("Daughter", "Daughter"),
                            ("Sister", "Sister"),
                            ("Brother", "Brother"),
                            ("Friend", "Friend"),
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                        ],
                        default="personal",
                        max_length=128,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("mobile_number", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserFamily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "familyType",
                    models.CharField(
                        blank=True,
                        choices=[("Nuclear Family", "Nuclear Family"), ("Joint Family", "Joint Family"), ("Extended Family", "Extended Family"), ("Other", "Other")],
                        default="Nuclear Family",
                        max_length=225,
                        null=True,
                    ),
                ),
                (
                    "relegion",
                    models.CharField(
                        choices=[
                            ("Islam", "Islam"),
                            ("Hindu", "Hindu"),
                            ("Cristian", "Cristian"),
                            ("Jainism", "Jainism"),
                            ("Buddhist", "Buddhist"),
                            ("Parsi", "Parsi"),
                            ("Sikhism ", "Sikhism "),
                            ("Others ", "Others "),
                            ("Preferred not to say", "Preferred not to say"),
                        ],
                        default="Islam",
                        max_length=225,
                    ),
                ),
                (
                    "fatherOccupation",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("Self Employee", "Self Employee"),
                            ("NRI", "NRI"),
                            ("Home Maker", "Home Maker"),
                            ("Govt Employee", "Govt Employee"),
                            ("Retired", "Retired"),
                            ("Buisness", "Buisness"),
                            ("Coolie", "Coolie"),
                            ("Farmer", "Farmer"),
                            ("Others", "Others"),
                        ],
                        default="Private",
                        max_length=225,
                    ),
                ),
                (
                    "motherOccupation",
                    models.CharField(
                        choices=[
                            ("House Wife", "House Wife"),
                            ("Private", "Private"),
                            ("Self Employee", "Self Employee"),
                            ("NRI", "NRI"),
                            ("Home Maker", "Home Maker"),
                            ("Govt Employee", "Govt Employee"),
                            ("Retired", "Retired"),
                            ("Buisness", "Buisness"),
                            ("Coolie", "Coolie"),
                            ("Farmer", "Farmer"),
                            ("Others", "Others"),
                        ],
                        default="House Wife",
                        max_length=225,
                    ),
                ),
                ("numberof_brothers", models.IntegerField(blank=True, null=True)),
                ("numberof_sisters", models.IntegerField(blank=True, null=True)),
                ("family_status", models.CharField(max_length=200)),
                ("register", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.register")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name_plural": "User family details"},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_of_children", models.IntegerField(blank=True, null=True)),
                ("bismID", models.CharField(default="BISM1000", max_length=10)),
                ("height", models.IntegerField()),
                ("gender", models.CharField(choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")], default="male", max_length=100)),
                ("weight", models.IntegerField()),
                (
                    "community",
                    models.CharField(
                        choices=[
                            ("AMuslim", "A Muslim"),
                            ("Sunni", "Sunni"),
                            ("Sunni (EK)", "Sunni (EK)"),
                            ("Sunni (AP)", "Sunni (AP)"),
                            ("Salafi (KNM)", "Salafi (KNM)"),
                            ("Salafi (Markaz dawa)", "Salafi (Markaz dawa)"),
                            ("Salafi (Wisdom)", "Salafi (Wisdom)"),
                            ("Jamayath Islam ", "Jamayath Islam "),
                            ("Thableeg Jamath ", "Thableeg Jamath "),
                            ("Maliki", "Maliki"),
                            ("Hanafi", "Hanafi"),
                            ("Sayyid", "Sayyid"),
                            ("Soofism", "Soofism"),
                            ("Other", "Other"),
                        ],
                        default="Shafi",
                        max_length=225,
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("Single", "Single"), ("Divorced", "Divorced"), ("Married", "Married"), ("Widow", "Widow")], default="Single", max_length=225),
                ),
                ("bodyType", models.CharField(choices=[("slim", "Slim"), ("Muscular", "Muscular"), ("Fat", "Fat"), ("Normal", "Normal")], default="slim", max_length=225)),
                (
                    "physical_status",
                    models.CharField(
                        choices=[
                            ("Sound", "Sound"),
                            ("Challenged", "Challenged"),
                            ("Blind", "Blind"),
                            ("PhysicallyChallenged", "Physically Challenged"),
                            ("MentallyChallenged", "Mentally Challenged"),
                            ("OtherDisabilities", "Other Disabilities"),
                        ],
                        default="slim",
                        max_length=225,
                    ),
                ),
                ("motherTongue", models.CharField(max_length=225)),
                ("language_known", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Occasionally", "Occasionally"), ("Addicted", "Addicted"), ("Social", "Social")],
                        max_length=225,
                        null=True,
                    ),
                ),
                (
                    "drinking",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Occasionally", "Occasionally"), ("Addicted", "Addicted"), ("Social", "Social")],
                        max_length=225,
                        null=True,
                    ),
                ),
                (
                    "readQuran",
                    models.CharField(
                        choices=[
                            ("Always", "Always"),
                            ("Sometimes", "Sometimes"),
                            ("Only Friday", "Only Friday"),
                            ("During Ramadan", "During Ramadan"),
                            ("Never", "Never"),
                            ("Prefer not to say", "Prefer not to say"),
                        ],
                        default="Yes",
                        max_length=225,
                    ),
                ),
                ("islamic_services", models.CharField(choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=225)),
                (
                    "complexion",
                    models.CharField(
                        choices=[
                            ("Fair skin", "Fair skin"),
                            ("Extremely fair skin", "Extremely fair skin"),
                            ("Black skin", "Black skin"),
                            ("Medium skin", "Medium skin"),
                            ("Olive skin", "Olive skin"),
                            ("Brown skin", "Brown skin"),
                        ],
                        default="Medium skin",
                        max_length=225,
                    ),
                ),
                (
                    "perform_namaz",
                    models.CharField(
                        choices=[("Always", "Always"), ("Sometimes", "Sometimes"), ("Never", "Never"), ("Prefer not to say", "Prefer not to say")], default="Always", max_length=225
                    ),
                ),
                (
                    "fasting",
                    models.CharField(
                        choices=[("Always", "Always"), ("Sometimes", "Sometimes"), ("Never", "Never"), ("Prefer not to say", "Prefer not to say")], default="Always", max_length=225
                    ),
                ),
                ("register", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.register")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ViewedProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "highestEducation",
                    models.CharField(
                        choices=[
                            ("Masters", "Masters"),
                            ("Doctorate", "Doctorate"),
                            ("Bachelors", "Bachelors"),
                            ("Diploma", "Diploma"),
                            ("ITI", "ITI"),
                            ("Islamic Education", "Islamic Education"),
                            ("High School", "High School"),
                            ("Other", "Other"),
                        ],
                        default="plustwo",
                        max_length=225,
                    ),
                ),
                ("profession", models.CharField(max_length=255)),
                (
                    "working_with",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NotWorking", "Not Working"),
                            ("PrivateSector", "Private Sector"),
                            ("PublicSector", "Public Sector"),
                            ("CivilService", "Civil Service"),
                            ("Defence", "Defence"),
                            ("Business", "Business"),
                            ("SelfEmployed", "Self Employed"),
                            ("NRI", "NRI"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "working_as",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NotWorking", "Not Working"),
                            ("Accountant", "Accountant"),
                            ("CA", "CA"),
                            ("Secretary", "Secretary"),
                            ("Doctor", "Doctor"),
                            ("Nurse", "Nurse"),
                            ("Marketingexecutive", "Marketing Executive"),
                            ("HRM", "HRM"),
                            ("Pharmacist", "Pharmacist"),
                            ("Self employed", "Self Employed"),
                            ("Parttime", "Part Time"),
                            ("Professor", "Professor"),
                            ("Teacher", "Teacher"),
                            ("Softwaredeveloper", "Software Developer"),
                            ("Graphicsdesigner", "Graphics Designer"),
                            ("Administrator", "Administrator"),
                            ("Business", "Business"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("annual_income", models.CharField(blank=True, max_length=225, null=True)),
                ("register", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.register")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("user_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
            ],
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_home_name", models.CharField(max_length=255)),
                ("current_city", models.CharField(max_length=255)),
                ("current_locality", models.CharField(max_length=255)),
                ("home_name", models.CharField(max_length=255)),
                ("native_city", models.CharField(max_length=255)),
                ("native_locality", models.CharField(max_length=255)),
                ("primary_number", models.CharField(max_length=255)),
                ("secondary_number", models.CharField(blank=True, max_length=255, null=True)),
                ("preffered_person", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "relation",
                    models.CharField(
                        blank=True, choices=[("Parent", "Parent"), ("Brother", "Brother"), ("Self", "Self"), ("Sister", "Sister"), ("Friend", "Friend")], max_length=225, null=True
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=128, null=True)),
                ("about", models.TextField()),
                ("pincode", models.CharField(max_length=100)),
                ("register", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.register")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("user_family", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userfamily")),
                ("user_profession", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofession")),
                ("user_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
            ],
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_one", versatileimagefield.fields.VersatileImageField(blank=True, default="default.jpg", upload_to="userimage")),
                ("image_one_ppoi", versatileimagefield.fields.PPOIField(default="0.5x0.5", editable=False, max_length=20)),
                ("image_two", versatileimagefield.fields.VersatileImageField(blank=True, default="default.jpg", upload_to="userimage")),
                ("image_two_ppoi", versatileimagefield.fields.PPOIField(default="0.5x0.5", editable=False, max_length=20)),
                ("image_three", versatileimagefield.fields.VersatileImageField(blank=True, default="default.jpg", upload_to="userimage")),
                ("image_three_ppoi", versatileimagefield.fields.PPOIField(default="0.5x0.5", editable=False, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("register", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.register")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("user_family", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userfamily")),
                ("user_location", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userlocation")),
                ("user_profession", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofession")),
                ("user_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
            ],
        ),
        migrations.AddField(model_name="userfamily", name="user_profession", field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofession")),
        migrations.AddField(model_name="userfamily", name="user_profile", field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
        migrations.CreateModel(
            name="PartnerPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("age_from", models.IntegerField()),
                ("age_to", models.IntegerField()),
                (
                    "marital_status",
                    models.CharField(choices=[("Single", "Single"), ("Divorced", "Divorced"), ("Married", "Married"), ("Widow", "Widow")], default="parent", max_length=225),
                ),
                ("height_from", models.IntegerField()),
                ("height_to", models.IntegerField()),
                (
                    "complexion",
                    models.CharField(
                        choices=[
                            ("Fair skin", "Fair skin"),
                            ("Extremely fair skin", "Extremely fair skin"),
                            ("Black skin", "Black skin"),
                            ("Medium skin", "Medium skin"),
                            ("Olive skin", "Olive skin"),
                            ("Brown skin", "Brown skin"),
                        ],
                        default="Medium skin",
                        max_length=225,
                    ),
                ),
                (
                    "highestEducation",
                    models.CharField(
                        choices=[
                            ("Masters", "Masters"),
                            ("Doctorate", "Doctorate"),
                            ("Bachelors", "Bachelors"),
                            ("Diploma", "Diploma"),
                            ("ITI", "ITI"),
                            ("Islamic Education", "Islamic Education"),
                            ("High School", "High School"),
                            ("Other", "Other"),
                        ],
                        default="plustwo",
                        max_length=225,
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("NotWorking", "Not Working"),
                            ("Accountant", "Accountant"),
                            ("CA", "CA"),
                            ("Secretary", "Secretary"),
                            ("Doctor", "Doctor"),
                            ("Nurse", "Nurse"),
                            ("Marketingexecutive", "Marketing Executive"),
                            ("HRM", "HRM"),
                            ("Pharmacist", "Pharmacist"),
                            ("Self employed", "Self Employed"),
                            ("Parttime", "Part Time"),
                            ("Professor", "Professor"),
                            ("Teacher", "Teacher"),
                            ("Softwaredeveloper", "Software Developer"),
                            ("Graphicsdesigner", "Graphics Designer"),
                            ("Administrator", "Administrator"),
                            ("Business", "Business"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "community",
                    models.CharField(
                        choices=[
                            ("AMuslim", "A Muslim"),
                            ("Sunni", "Sunni"),
                            ("Sunni (EK)", "Sunni (EK)"),
                            ("Sunni (AP)", "Sunni (AP)"),
                            ("Salafi (KNM)", "Salafi (KNM)"),
                            ("Salafi (Markaz dawa)", "Salafi (Markaz dawa)"),
                            ("Salafi (Wisdom)", "Salafi (Wisdom)"),
                            ("Jamayath Islam ", "Jamayath Islam "),
                            ("Thableeg Jamath ", "Thableeg Jamath "),
                            ("Maliki", "Maliki"),
                            ("Hanafi", "Hanafi"),
                            ("Sayyid", "Sayyid"),
                            ("Soofism", "Soofism"),
                            ("Other", "Other"),
                        ],
                        default="Shafi",
                        max_length=225,
                    ),
                ),
                ("Location", models.CharField(max_length=255)),
                ("body_type", models.CharField(choices=[("slim", "Slim"), ("Muscular", "Muscular"), ("Fat", "Fat"), ("Normal", "Normal")], max_length=50)),
                ("register", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.register")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("user_family", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userfamily")),
                ("user_location", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userlocation")),
                ("user_profession", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofession")),
                ("user_profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
            ],
        ),
        migrations.CreateModel(
            name="LikedProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(model_name="user", name="register", field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="user.register")),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
