# Generated by Django 3.2.8 on 2021-12-14 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("user", "0002_auto_20211203_1059")]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("roome_name", models.CharField(max_length=128, unique=True)),
                ("chat_user_one", models.IntegerField()),
                ("chat_user_two", models.IntegerField()),
                ("lastUpdated", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-lastUpdated"], "unique_together": {("chat_user_one", "chat_user_two")}},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("time", models.TimeField(auto_now=True)),
                ("chat", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.chat")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-time"]},
        ),
    ]
