# Generated by Django 3.2.8 on 2021-12-18 09:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("user", "0003_chat_message")]

    operations = [
        migrations.AddField(model_name="userimage", name="date", field=models.DateField(auto_now=True)),
        migrations.AlterField(
            model_name="partnerpreference",
            name="complexion",
            field=models.CharField(
                choices=[
                    ("Fair skin", "Fair skin"),
                    ("Extremely fair skin", "Extremely fair skin"),
                    ("Black skin", "Black skin"),
                    ("Medium skin", "Medium skin"),
                    ("Olive skin", "Olive skin"),
                    ("Brown skin", "Brown skin"),
                ],
                max_length=225,
            ),
        ),
    ]
