# Generated by Django 3.2.8 on 2021-12-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211223_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpreference',
            name='age_from',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='age_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='body_type',
            field=models.CharField(choices=[('slim', 'Slim'), ('Muscular', 'Muscular'), ('Fat', 'Fat'), ('Normal', 'Normal')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='community',
            field=models.CharField(choices=[('AMuslim', 'A Muslim'), ('Sunni', 'Sunni'), ('Sunni (EK)', 'Sunni (EK)'), ('Sunni (AP)', 'Sunni (AP)'), ('Salafi (KNM)', 'Salafi (KNM)'), ('Salafi (Markaz dawa)', 'Salafi (Markaz dawa)'), ('Salafi (Wisdom)', 'Salafi (Wisdom)'), ('Jamayath Islam ', 'Jamayath Islam '), ('Thableeg Jamath ', 'Thableeg Jamath '), ('Maliki', 'Maliki'), ('Hanafi', 'Hanafi'), ('Sayyid', 'Sayyid'), ('Soofism', 'Soofism'), ('Other', 'Other')], default='Shafi', max_length=225),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='complexion',
            field=models.CharField(choices=[('Fair skin', 'Fair skin'), ('Extremely fair skin', 'Extremely fair skin'), ('Black skin', 'Black skin'), ('Medium skin', 'Medium skin'), ('Olive skin', 'Olive skin'), ('Brown skin', 'Brown skin')], default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='height_from',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='height_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='highestEducation',
            field=models.CharField(choices=[('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('ITI', 'ITI'), ('Islamic Education', 'Islamic Education'), ('High School', 'High School'), ('Other', 'Other')], default='plustwo', max_length=225),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='location',
            field=models.CharField(choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Malappuram', 'Malappuram'), ('Ernakulam', 'Ernakulam'), ('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thrissur', 'Thrissur'), ('Thiruvananthapuram', 'Thiruvananthapuram')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widow', 'Widow')], default='parent', max_length=225),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='profession',
            field=models.CharField(choices=[('NotWorking', 'Not Working'), ('Accountant', 'Accountant'), ('CA', 'CA'), ('Secretary', 'Secretary'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Marketingexecutive', 'Marketing Executive'), ('HRM', 'HRM'), ('Pharmacist', 'Pharmacist'), ('Self employed', 'Self Employed'), ('Parttime', 'Part Time'), ('Professor', 'Professor'), ('Teacher', 'Teacher'), ('Softwaredeveloper', 'Software Developer'), ('Graphicsdesigner', 'Graphics Designer'), ('Administrator', 'Administrator'), ('Business', 'Business'), ('Driver', 'Driver'), ('Coolie', 'Coolie'), ('Farmer', 'Farmer'), ('Consultant', 'Consultant'), ('Sales Person', 'Sales Person'), ('Tax Consultant', 'Tax Consultant'), ('Bank Employee', 'Bank Employee'), ('Engineer', 'Engineer'), ('Trainer', 'Trainer'), ('Service Advicer', 'Service Advicer'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Chef', 'Chef')], default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='register',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_family',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userfamily'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userlocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_profession',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userprofession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
            preserve_default=False,
        ),
    ]
