# Generated by Django 3.2.8 on 2021-12-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211223_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpreference',
            name='age_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='body_type',
            field=models.CharField(blank=True, choices=[('slim', 'Slim'), ('Muscular', 'Muscular'), ('Fat', 'Fat'), ('Normal', 'Normal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='community',
            field=models.CharField(blank=True, choices=[('AMuslim', 'A Muslim'), ('Sunni', 'Sunni'), ('Sunni (EK)', 'Sunni (EK)'), ('Sunni (AP)', 'Sunni (AP)'), ('Salafi (KNM)', 'Salafi (KNM)'), ('Salafi (Markaz dawa)', 'Salafi (Markaz dawa)'), ('Salafi (Wisdom)', 'Salafi (Wisdom)'), ('Jamayath Islam ', 'Jamayath Islam '), ('Thableeg Jamath ', 'Thableeg Jamath '), ('Maliki', 'Maliki'), ('Hanafi', 'Hanafi'), ('Sayyid', 'Sayyid'), ('Soofism', 'Soofism'), ('Other', 'Other')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='complexion',
            field=models.CharField(blank=True, choices=[('Fair skin', 'Fair skin'), ('Extremely fair skin', 'Extremely fair skin'), ('Black skin', 'Black skin'), ('Medium skin', 'Medium skin'), ('Olive skin', 'Olive skin'), ('Brown skin', 'Brown skin')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='height_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='height_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='highestEducation',
            field=models.CharField(blank=True, choices=[('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('ITI', 'ITI'), ('Islamic Education', 'Islamic Education'), ('High School', 'High School'), ('Other', 'Other')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='location',
            field=models.CharField(blank=True, choices=[('Kasaragod', 'Kasaragod'), ('Kannur', 'Kannur'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Malappuram', 'Malappuram'), ('Ernakulam', 'Ernakulam'), ('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thrissur', 'Thrissur'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widow', 'Widow')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='profession',
            field=models.CharField(blank=True, choices=[('NotWorking', 'Not Working'), ('Accountant', 'Accountant'), ('CA', 'CA'), ('Secretary', 'Secretary'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Marketingexecutive', 'Marketing Executive'), ('HRM', 'HRM'), ('Pharmacist', 'Pharmacist'), ('Self employed', 'Self Employed'), ('Parttime', 'Part Time'), ('Professor', 'Professor'), ('Teacher', 'Teacher'), ('Softwaredeveloper', 'Software Developer'), ('Graphicsdesigner', 'Graphics Designer'), ('Administrator', 'Administrator'), ('Business', 'Business'), ('Driver', 'Driver'), ('Coolie', 'Coolie'), ('Farmer', 'Farmer'), ('Consultant', 'Consultant'), ('Sales Person', 'Sales Person'), ('Tax Consultant', 'Tax Consultant'), ('Bank Employee', 'Bank Employee'), ('Engineer', 'Engineer'), ('Trainer', 'Trainer'), ('Service Advicer', 'Service Advicer'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Chef', 'Chef')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='register',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.register'),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_family',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userfamily'),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userlocation'),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_profession',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofession'),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile'),
        ),
    ]
