# Generated by Django 3.2.8 on 2021-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211223_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfamily',
            name='relegion',
            field=models.CharField(choices=[('Very Religious', 'Very Religious'), ('Religious', 'Relegious'), ('Liberal', 'Liberal'), ('Prefer not to say', 'Prefer not to say'), ('Not Religious', 'Not Religious')], default='Islam', max_length=225),
        ),
        migrations.AlterField(
            model_name='userprofession',
            name='working_as',
            field=models.CharField(blank=True, choices=[('NotWorking', 'Not Working'), ('Accountant', 'Accountant'), ('CA', 'CA'), ('Secretary', 'Secretary'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Marketingexecutive', 'Marketing Executive'), ('HRM', 'HRM'), ('Pharmacist', 'Pharmacist'), ('Self employed', 'Self Employed'), ('Parttime', 'Part Time'), ('Professor', 'Professor'), ('Teacher', 'Teacher'), ('Softwaredeveloper', 'Software Developer'), ('Graphicsdesigner', 'Graphics Designer'), ('Administrator', 'Administrator'), ('Business', 'Business'), ('Driver', 'Driver'), ('Coolie', 'Coolie'), ('Farmer', 'Farmer'), ('Consultant', 'Consultant'), ('Sales Person', 'Sales Person'), ('Tax Consultant', 'Tax Consultant'), ('Bank Employee', 'Bank Employee'), ('Engineer', 'Engineer'), ('Trainer', 'Trainer'), ('Service Advicer', 'Service Advicer'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Chef', 'Chef'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofession',
            name='working_with',
            field=models.CharField(blank=True, choices=[('NotWorking', 'Not Working'), ('PrivateSector', 'Private Sector'), ('PublicSector', 'Public Sector'), ('CivilService', 'Civil Service'), ('Defence', 'Defence'), ('Business', 'Business'), ('SelfEmployed', 'Self Employed'), ('NRI', 'NRI'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_status',
            field=models.CharField(choices=[('Sound/Normal', 'Sound/Normal'), ('Blind', 'Blind'), ('PhysicallyChallenged', 'Physically Challenged'), ('MentallyChallenged', 'Mentally Challenged'), ('OtherDisabilities', 'Other Disabilities')], default='slim', max_length=225),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widow', 'Widow')], default='Single', max_length=225),
        ),
    ]
