# Generated by Django 3.2.8 on 2021-12-27 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("user", "0010_auto_20211226_1738")]

    operations = [
        migrations.CreateModel(
            name="PassedProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("passed_by_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("passed_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.userprofile")),
            ],
        )
    ]
